from collections.abc import AsyncIterator
from contextlib import AbstractAsyncContextManager
from typing import Protocol
from uuid import UUID
from api.domain.entities import Account, Transaction, TransactionStatus

class AccountRepository(Protocol):
    async def add(self, account: Account)->None: ...
    async def get(self, account_id: UUID)-> Account | None: ...
    async def get_for_update(self, account_id: UUID)-> Account | None: ...
    async def save(self, account: Account)-> None: ...

class TransactionRepository(Protocol):
    async def add(self, transaction:Transaction)->None:...
    async def get(self, transaction_id:UUID)->Transaction|None:...
    async def get_by_idempotency_key(self, idempotency_key: str)->Transaction|None:...
    async def save(self, transaction:Transaction)->None:...
    async def list_by_status(self, status: TransactionStatus, limit: int)->list[Transaction]:...

class UnitOfWork(Protocol):
    accounts: AccountRepository
    transactions: TransactionRepository

    async def __aenter__(self)->"UnitOfWork":...
    async def __aexit__(self, exc_type: object, exc: object, tb: object)->None:...
    async def commit(self)->None:...
    async def rollback(self)->None:...

class TransactionQueue(Protocol):
    async def enqueue(self, transaction_id: UUID)->None:...
    async def dequeue(self)->None:...
    def size(self)->int:...
    async def healthcheck(self)->None:...

class TransactionExporter(Protocol):
    async def export(self, transaction:Transaction)->None:...

class AccountLockProvider(Protocol):
    def lock_pair(
        self,
        first: UUID,
        second: UUID,
    ) -> AbstractAsyncContextManager[None]:
        ...